/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as HostRouteImport } from './routes/host'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostIndexRouteImport } from './routes/host/index'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as HostVerificationRouteImport } from './routes/host/verification'
import { Route as HostReviewsRouteImport } from './routes/host/reviews'
import { Route as HostPropertiesRouteImport } from './routes/host/properties'
import { Route as HostMessagesRouteImport } from './routes/host/messages'
import { Route as HostCalendarRouteImport } from './routes/host/calendar'
import { Route as HostBookingsRouteImport } from './routes/host/bookings'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostIndexRoute = HostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HostRoute,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HostVerificationRoute = HostVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => HostRoute,
} as any)
const HostReviewsRoute = HostReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => HostRoute,
} as any)
const HostPropertiesRoute = HostPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => HostRoute,
} as any)
const HostMessagesRoute = HostMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => HostRoute,
} as any)
const HostCalendarRoute = HostCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => HostRoute,
} as any)
const HostBookingsRoute = HostBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => HostRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guest': typeof GuestRoute
  '/host': typeof HostRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/host/bookings': typeof HostBookingsRoute
  '/host/calendar': typeof HostCalendarRoute
  '/host/messages': typeof HostMessagesRoute
  '/host/properties': typeof HostPropertiesRoute
  '/host/reviews': typeof HostReviewsRoute
  '/host/verification': typeof HostVerificationRoute
  '/listing/$id': typeof ListingIdRoute
  '/host/': typeof HostIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guest': typeof GuestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/host/bookings': typeof HostBookingsRoute
  '/host/calendar': typeof HostCalendarRoute
  '/host/messages': typeof HostMessagesRoute
  '/host/properties': typeof HostPropertiesRoute
  '/host/reviews': typeof HostReviewsRoute
  '/host/verification': typeof HostVerificationRoute
  '/listing/$id': typeof ListingIdRoute
  '/host': typeof HostIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guest': typeof GuestRoute
  '/host': typeof HostRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/host/bookings': typeof HostBookingsRoute
  '/host/calendar': typeof HostCalendarRoute
  '/host/messages': typeof HostMessagesRoute
  '/host/properties': typeof HostPropertiesRoute
  '/host/reviews': typeof HostReviewsRoute
  '/host/verification': typeof HostVerificationRoute
  '/listing/$id': typeof ListingIdRoute
  '/host/': typeof HostIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/explore'
    | '/forgot-password'
    | '/guest'
    | '/host'
    | '/reset-password'
    | '/verify-email'
    | '/host/bookings'
    | '/host/calendar'
    | '/host/messages'
    | '/host/properties'
    | '/host/reviews'
    | '/host/verification'
    | '/listing/$id'
    | '/host/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/explore'
    | '/forgot-password'
    | '/guest'
    | '/reset-password'
    | '/verify-email'
    | '/host/bookings'
    | '/host/calendar'
    | '/host/messages'
    | '/host/properties'
    | '/host/reviews'
    | '/host/verification'
    | '/listing/$id'
    | '/host'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/explore'
    | '/forgot-password'
    | '/guest'
    | '/host'
    | '/reset-password'
    | '/verify-email'
    | '/host/bookings'
    | '/host/calendar'
    | '/host/messages'
    | '/host/properties'
    | '/host/reviews'
    | '/host/verification'
    | '/listing/$id'
    | '/host/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ExploreRoute: typeof ExploreRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GuestRoute: typeof GuestRoute
  HostRoute: typeof HostRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ListingIdRoute: typeof ListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/': {
      id: '/host/'
      path: '/'
      fullPath: '/host/'
      preLoaderRoute: typeof HostIndexRouteImport
      parentRoute: typeof HostRoute
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/verification': {
      id: '/host/verification'
      path: '/verification'
      fullPath: '/host/verification'
      preLoaderRoute: typeof HostVerificationRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/reviews': {
      id: '/host/reviews'
      path: '/reviews'
      fullPath: '/host/reviews'
      preLoaderRoute: typeof HostReviewsRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/properties': {
      id: '/host/properties'
      path: '/properties'
      fullPath: '/host/properties'
      preLoaderRoute: typeof HostPropertiesRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/messages': {
      id: '/host/messages'
      path: '/messages'
      fullPath: '/host/messages'
      preLoaderRoute: typeof HostMessagesRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/calendar': {
      id: '/host/calendar'
      path: '/calendar'
      fullPath: '/host/calendar'
      preLoaderRoute: typeof HostCalendarRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/bookings': {
      id: '/host/bookings'
      path: '/bookings'
      fullPath: '/host/bookings'
      preLoaderRoute: typeof HostBookingsRouteImport
      parentRoute: typeof HostRoute
    }
  }
}

interface HostRouteChildren {
  HostBookingsRoute: typeof HostBookingsRoute
  HostCalendarRoute: typeof HostCalendarRoute
  HostMessagesRoute: typeof HostMessagesRoute
  HostPropertiesRoute: typeof HostPropertiesRoute
  HostReviewsRoute: typeof HostReviewsRoute
  HostVerificationRoute: typeof HostVerificationRoute
  HostIndexRoute: typeof HostIndexRoute
}

const HostRouteChildren: HostRouteChildren = {
  HostBookingsRoute: HostBookingsRoute,
  HostCalendarRoute: HostCalendarRoute,
  HostMessagesRoute: HostMessagesRoute,
  HostPropertiesRoute: HostPropertiesRoute,
  HostReviewsRoute: HostReviewsRoute,
  HostVerificationRoute: HostVerificationRoute,
  HostIndexRoute: HostIndexRoute,
}

const HostRouteWithChildren = HostRoute._addFileChildren(HostRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ExploreRoute: ExploreRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GuestRoute: GuestRoute,
  HostRoute: HostRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ListingIdRoute: ListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
